name: gabriel-tut
version: '0.1.0.0'
category: Web
author: Daniel Vianna
maintainer: dmlvianna <at> gmail <dot> com
copyright: MIT
license: BSD3
homepage: https://github.com/dmvianna/gabriel-tut#readme
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
- bytestring
- containers
- text
- vector
- cassava
- diagrams-lib
- diagrams-svg
executables:
  gabriel-tut:
    main: Main.hs
    source-dirs: src
